packages:
  - hygen
allowBuilds:
  esbuild: true
  ttf2woff2: false
minimumReleaseAgeExclude:
  - '@xmldom/xmldom@0.8.12 || 0.8.13'
overrides:
  '@xmldom/xmldom@<0.8.12': ^0.8.12
  '@xmldom/xmldom@<0.8.13': ^0.8.13
  file-type: 16.5.4
