name: Leaked Secrets Scan

on:
  workflow_call:

jobs:
  TruffleHog:
    name: Secrets Scan
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/trufflehog-oss#advanced-usage-scan-entire-branch
      - name: 🐷 TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.90.11
        if: ${{ github.event.pull_request != null }} # only scan on pull-requests
        with:
          # Setting base to an empty string scans the entire branch, per TruffleHog OSS advanced usage:
          # https://github.com/marketplace/actions/trufflehog-oss#advanced-usage-scan-entire-branch
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
