name: Leaked Secrets Scan

on:
  workflow_call:

jobs:
  TruffleHog:
    name: Secrets Scan
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/trufflehog-oss#advanced-usage-scan-entire-branch
      - name: 🐷 TruffleHog OSS
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # v3.95.9
        if: ${{ github.event.pull_request != null }} # only scan on pull-requests
        with:
          # Setting base to an empty string scans the entire branch, per TruffleHog OSS advanced usage:
          # https://github.com/marketplace/actions/trufflehog-oss#advanced-usage-scan-entire-branch
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
