---
name: Build Workflow

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v6

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - name: 🔨 Build all
        run: pnpm build

      - name: 🆙 Upload dist
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: dist
          retention-days: 7
