---
name: Test

on:
  workflow_call:

jobs:
  validate:
    name: Test
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: ⏬ Install fonttools
        run: |
          pip3 install fonttools brotli
          fonttools --help

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - name: 👨‍🔬👩‍🔬 Test repo
        run: pnpm run test
