---
name: Test

on:
  workflow_call:

jobs:
  validate:
    name: Test
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: ⏬ Install fonttools
        run: |
          pip3 install fonttools brotli
          fonttools --help

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - name: 👨‍🔬👩‍🔬 Test repo
        run: pnpm run test
