---
name: 'Pull Request Labeler'
on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: 🏷️ Labeler
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
